### ISSUE TITLE
Cannot find "install" when installing Virtualbox SDK

### ISSUE THREAD

**Issue by AcezukyRockon** [bukanspot/DiscordBox#7]
[Issue]:
- When run command "python vboxapisetup.py install" inside folder sdk\installer\python with python > 3.12, it will give an error about cannot find "Install" at this line
- setup.py:
![Image](https://github.com/user-attachments/assets/3469b40d-a85d-492a-82e5-8b4c6e187dd6)

[Current workaround]
- Use python below version 3.12 (currently I tried and worked with python 3.10.11) for command "python vboxapisetup.py install". It may gives an Error "ERROR: Testing VirtualBox Python bindings failed: cannot import name 'VirtualBoxManager' from 'vboxapi' (unknown location)" but it's OK. Now you can process to next step at DiscordBox.

**Comment by HReborn** [comment]
It worked for me. It gave me a deprecated error though. Before running the command, i had to install a module with 
`python -m pip install -U pip setuptools`

<img width="1102" height="457" alt="Image" src="https://github.com/user-attachments/assets/9067a8b9-73f9-4aac-8a4e-dcd34039cb7d" />
